/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BibleReferencePicker {
    }
}
declare global {
    interface HTMLBibleReferencePickerElement extends Components.BibleReferencePicker, HTMLStencilElement {
    }
    var HTMLBibleReferencePickerElement: {
        prototype: HTMLBibleReferencePickerElement;
        new (): HTMLBibleReferencePickerElement;
    };
    interface HTMLElementTagNameMap {
        "bible-reference-picker": HTMLBibleReferencePickerElement;
    }
}
declare namespace LocalJSX {
    interface BibleReferencePicker {
    }
    interface IntrinsicElements {
        "bible-reference-picker": BibleReferencePicker;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bible-reference-picker": LocalJSX.IntrinsicElements["bible-reference-picker"] & JSXBase.HTMLAttributes<HTMLBibleReferencePickerElement>;
        }
    }
}
